google-research/arxiv-latex-cleaner

arxiv_latex_cleaner.py
tex/main.tex
tex_arXiv_true/main.tex

This PR introduces the possibility to delete user-defined custom commands that contain nested commands (e.g., `\textit{}`, `\texttt{}`) as reported in the issue #9.
I have improved the regex that matches the custom command as well as the one that matches the `\begin{}...\end{}` environment.
The only limitation is that a maximum of two nested levels is supported, which seems to be reasonable in most of the scenarios.

Fix issue #9 (commands inside commands)

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py

In some cases, ghostscript will automatically rotate some pages in some PDF files. This becomes annoying when a PDF figure suddenly changes orientation in the paper. The flag `-dAutoRotatePages=/None` prevents this behavior so that the orientation is retained.

Prevent ghostscript from auto-rotating pages

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py
tex/main.tex
tex_arXiv_true/main.tex

Closes #12 by removing possibly nested
```
\iffalse
*
\fi
```
blocks.

Add removal of iffalse

---

arxiv_latex_cleaner/__main__.py

Fix a regression introduced by commit 8310b0f8be3682165c9022d4053d7bab26c9798f which removed the --use_external_tikz command-line switch

Fix external_tikz regression

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
cleaner_config.yaml

This PR adds a new flag `strip_whitespace` for pattern replacement.

Optionally disable strip_whitespace for pattern replacement

---

arxiv_latex_cleaner/__main__.py
arxiv_latex_cleaner/arxiv_latex_cleaner.py

This PR follows @jponttuset comment https://github.com/google-research/arxiv-latex-cleaner/issues/28#issuecomment-667578262 and fixes https://github.com/google-research/arxiv-latex-cleaner/issues/28. 
In detail, if the user calls the module with the option `--keep_bib` the bib files are not deleted.

Add the option to keep the bib files

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py

The previous order of args did not capture `-dAutoRotatePages=/None`. It leads to unexpected behavior when compressing a pdf with a vertical major orientation of the text.

Fix the order of args in gs to actually disable AutoRotatePages

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
tex/main.tex

This pull request fixes https://github.com/google-research/arxiv-latex-cleaner/issues/45. 
This bug deletes all the content after a line like `% here is \end{document} in comment`.

Fixes#45: do not clean content after commented \end{document}.

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py

Sequel to #25, added more tests, discovered a bug in the process, fixed the bug, added some more tests.
In case you're curious about the bug, turns out `os.path.split` only splits a path into two parts. So `os.path.split("long/path/to")` will yield `"long/path", "to"`. And, earlier we were iterating over the result of `os.path.split` expecting to get all the parts one by one, i.e. `["long", "path", "to"]`. Now, we first collect all the path fragments and then loop over them.
```python
fragments = []
cur_head = os.path.dirname(filename)
while cur_head:
cur_head, tail = os.path.split(cur_head)
fragments.insert(0, tail)  # insert at the beginning
```

Fixes path split bug and add more tests for `_search_reference`

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py
tex/main.tex
tex_arXiv_true/main.tex

some files 'path/to/file' are referenced in tex as './path/to/file'
thus add prefix for relative paths starting with './' or '.\' to regex search

Fix relative filenames referenced with './' in tex

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
tex/main.tex

We often use "\if false" or "\if 0" which contain (several) spaces within the commands. This commit addresses this type of comment block and provides the corresponding unit tests.
This also fixes #52.

Remove "\if false" or "\if 0" blocks that contain spaces

---

arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py

Change text file comparison to get rid of end of line. Now, tests pass on Windows and Linux (need to be tested on MacOSX).

Change text file comparison to get rid of end of line.

---

README.md
arxiv_latex_cleaner/__main__.py
arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py
tex/main.tex
tex_arXiv_true/main.tex

I add a command-line option (--commands_only_to_delete) to delete user-defined LaTeX commands but retain the text wrapped in the commands. This is useful for commands that are meant to temporarily change text colors and formats (e.g., some user-defined \red command that makes the text red), which are common in collaborative writing to highlight different people's texts. Such commands should be removed upon submissions but the text within ought to be retained.
Usages are exactly the same as --commands_to_delete. Note that if the commands listed here duplicate that after commands_to_delete, the default action will be retaining the wrapped text.
1. `__main__.py`: add an option and related help text.
2. `arxiv_latex_cleaner.py`: add an optional parameter to the `_remove_command` function, and …

Add an option to delete commands but keep their wrapped text

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py
requirements.txt

Fixes #63
- Adds a test case for #63
- Implements a recursive regex pattern to match arbitrarily deeply nested commands, passing the new test case
- Switches to the `regex` package instead of `re` for support of recursive patterns

Fix --commands_to_delete failing to match deeply nested commands and hanging

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py

This PR adds `.fls` and `.fdb_latexmk` to the list of file extensions to delete.
These files are generated by default by `latexmk` and are not needed for recompilation. They contain paths to files and directories used during compilation. These paths might contain the system username.

Add .fls and .fdb_latexmk to list of extensions to delete

---

arxiv_latex_cleaner/__main__.py
arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py
tex/main.tex
tex_arXiv_true/main.tex

Add new argument `--environments_to_remove` to remove selected environments from the source file analogous to the existing functionality of `--commands_to_remove`.
---
This is pretty much the same as https://github.com/google-research/arxiv-latex-cleaner/pull/49, but the original author appears to have abandoned their PR. This PR hopefully addresses the concerns raised in the review there (mainly a testcase for the new argument).

Remove user-defined environments

---

README.md

Can be installed as `arxiv_latex_cleaner` using Homebrew per [54fb112](https://github.com/Homebrew/homebrew-core/commit/54fb112f004933e4b2c26fa68c7828439f28a724).

Adds Homebrew installation instructions

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py

This change resolves issue #82 by separating text into segments and not treating any % inside of \url{} as a comment.

Fixed issue #82: % inside of url link is not treated as comment

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py

This pull request addresses the issue where inline comments were not properly removed before a \url{} command.
Fixes issue #91.

Fix issue #91

---

README.md

First, thanks for your great tool! It's really helpful. While working with it, I observed a minor incorrectness. 
Motivation: In the current tikz documentation ([PGF manual](https://www.nic.funet.fi/pub/TeX/CTAN/graphics/pgf/base/doc/pgfmanual.pdf)), the section for externalisation changed to 52 instead of 53.

Correct section for tikz externalize

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py

This PR fixes #93. Two new test were added to ensure `auto-ignore` outside a comment tag is treated as normal text.

Fix issue #93

---

arxiv_latex_cleaner/arxiv_latex_cleaner.py
arxiv_latex_cleaner/tests/arxiv_latex_cleaner_test.py

Current svg_inkscape  option fails to convert  `\includesvg[test.svg]` to `includeinkscape[test_svg]` becase inkscape will convert test.svg to test_svg during conversion. 
This PR checks whether svg file ends with svg suffix and do the conversion if necessarily.
Tests are also added for this PR.

Fix svg_inkscape conversion with svg suffix
